[package]
name = "stellar-sign-cli-plugin"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
stellar-xdr = { version = "22.1.0", features = ["base64", "serde"] }
serde_json = "1.0.140"
